config/routes.rb
Rails.application.routes.draw do
  devise_for :talents
  devise_for :places
  root to: 'pages#home'

  get 'login', to: 'pages#login', as: 'login'

  resources :talents, only: %i[index show edit update] do
    resources :bookings, only: %i[new create]
  end

  resources :places, only: %i[index show edit update] do
    resources :promotions, only: %i[new create]
  end

  namespace :talent do
    get "dashboard", to: "pages#dashboard"
  end

  namespace :place do
    get "dashboard", to: "pages#dashboard"
  end

  # resources :bookings, only: :index # this route is for checking only
  # resources :promotions, only: :index # this route is for checking only

  resources :bookings, except: %i[new create index]
  resources :promotions, except: %i[new create index]
end

app/views/partials/_footer.html.erb
<footer class="bg-dark p-3">
    <small class="text-muted sticky_bottom">
      <p> Please note that the information on this website is not real,
      it is used to demonstrate the idea of the web application only,
      all rights belong to their owners.</p>
      <p> <a href="https://www.freepik.com/photos/singer" class="text-muted" target="_blank">Singers' photos are created by freepik - www.freepik.com</a></p>
      <p> <a href="https://www.freepik.com/photos/restaurant" class="text-muted" target="_blank">Restaurants' photos are created by freepik - www.freepik.com</a></p>
    </small>
</footer>

app/views/partials/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-lewagon sticky_top">
  <div class="container-fluid">
    <div class="talent_place_btn links_blue_to_white ps-1">
        <%= link_to root_path do %>
          <span class="fas fa-gem"></span> TalentPlace
        <% end %>
    </div>

    <button class="navbar-toggler p-1" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if talent_signed_in? %>
          <%= render "partials/navbar_signed_in_talent" %>
        <% elsif place_signed_in? %>
          <%= render "partials/navbar_signed_in_place" %>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", "#", class: "avatar dropdown-toggle dashboard_navbar_btn", id: "navbarDropdown", data: { bs_toggle: "dropdown" }%>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "as a talent", new_talent_session_path, class: "dropdown-item" %>
              <%= link_to "as a place", new_place_session_path, class: "dropdown-item" %>
            </div>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", "#",  class: "avatar dropdown-toggle dashboard_navbar_btn", id: "navbarDropdown", data: { bs_toggle: "dropdown" }%>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "as a talent", new_talent_registration_path, class: "dropdown-item" %>
              <%= link_to "as a place", new_place_registration_path, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/partials/_navbar_signed_in_place.html.erb
<li class="me-3">
  <%= link_to "Dashboard", place_dashboard_path, class: "dashboard_navbar_btn" %>
</li>
<li class="me-3">
  <%= link_to "Profile", place_path(current_place), class: "dashboard_navbar_btn" %>
</li>
<li class="nav-item dropdown">
  <%= cl_image_tag current_place.photo.key, class: "avatar dropdown-toggle navbar_profil_picture", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
  <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
    <%= link_to "Log out", destroy_place_session_path, method: :delete, class: "dropdown-item" %>
  </div>
</li>

app/views/partials/_navbar_signed_in_talent.html.erb
<%= link_to "Dashboard", talent_dashboard_path, class: "dashboard_navbar_btn me-3" %>
<%= link_to "Profile", talent_path(current_talent), class: "dashboard_navbar_btn me-3" %>
<div class="nav-item dropdown">
  <%= cl_image_tag current_talent.photo.key, class: "avatar dropdown-toggle navbar_profil_picture", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
  <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
    <%= link_to "Log out", destroy_talent_session_path, method: :delete, class: "dropdown-item" %>
  </div>
</div>