config/routes.rb
Rails.application.routes.draw do
  devise_for :talents
  devise_for :places
  root to: 'pages#home'

  get 'login', to: 'pages#login', as: 'login'

  resources :talents, only: %i[index show edit update] do
    resources :bookings, only: %i[new create]
  end

  resources :places, only: %i[index show edit update] do
    resources :promotions, only: %i[new create]
  end

  namespace :talent do
    get "dashboard", to: "pages#dashboard"
  end

  namespace :place do
    get "dashboard", to: "pages#dashboard"
  end

  # resources :bookings, only: :index # this route is for checking only
  # resources :promotions, only: :index # this route is for checking only

  resources :bookings, except: %i[new create index]
  resources :promotions, except: %i[new create index]
end

app/views/pages/home.html.erb
<div class="home-banner m-0">
  <%= image_tag("places/p10.jpeg", alt: "banner-img") %>
  <h1 class="over-image p-3">The platform to connect Talents [singers]<br>and Places [restaurants]</h1>
</div>
<div class="card-container">
  <div class="cards-home col-12 col-sm-6">
    <%= link_to talents_path, class: "card-home-body" do  %>
      <%= image_tag("talents/t19.jpeg", class: "card-img-top", alt: "places-img") %>
      <div class="placement-elements">
        <h5 class="card-title text-link mt-2">Looking for a musician for your place?</h5>
        <span class="btn-homepage purple_pink_btn">Find your talent!</span>
      </div>
    <% end %>
    <%= link_to places_path, class: "card-home-body" do %>
      <div class="placement-elements">
        <%= image_tag("places/p5.jpeg", class: "card-img-top", alt: "places-img") %>
        <h5 class="card-title text-link mt-2">Want to express your talent in public?</h5>
        <span class="btn-homepage purple_pink_btn">Find a place to play!</span>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/login.html.erb
<div class="home-banner">
  <%= image_tag("places/p10.jpeg", alt: "banner-img") %>
  <div class="over-image p-3">
    <% if current_place %>
      <h3>You are logged in as <%= current_place.title %> </h3>
    <% elsif current_talent %>
      <h3>You are logged in as <%= current_talent.name %> </h3>
    <% else %>
      <h3>Please log in</h3>
      <h3 class="m-5">as a <%= link_to 'talent', new_talent_session_path, class: "purple_pink_btn" %> (singer, musician, DJ)</h2>
      <h3>or</h3>
      <h3 class="m-5">as a <%= link_to 'place', new_place_session_path, class: "purple_pink_btn" %> (cafe, restaurant, bar)</h2>
    <% end %>
  </div>
</div>