config/routes.rb
Rails.application.routes.draw do
  devise_for :talents
  devise_for :places
  root to: 'pages#home'

  get 'login', to: 'pages#login', as: 'login'

  resources :talents, only: %i[index show edit update] do
    resources :bookings, only: %i[new create]
  end

  resources :places, only: %i[index show edit update] do
    resources :promotions, only: %i[new create]
  end

  namespace :talent do
    get "dashboard", to: "pages#dashboard"
  end

  namespace :place do
    get "dashboard", to: "pages#dashboard"
  end

  # resources :bookings, only: :index # this route is for checking only
  # resources :promotions, only: :index # this route is for checking only

  resources :bookings, except: %i[new create index]
  resources :promotions, except: %i[new create index]
end

app/models/talent.rb
class Talent < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :availabilities
  has_many :bookings, dependent: :delete_all
  has_many :promotions, dependent: :delete_all
  has_many :talent_genres, dependent: :delete_all
  has_many :genres, through: :talent_genres

  validates :photo, presence: true

  has_one_attached :photo
end

app/controllers/talent/pages_controller.rb
class Talent::PagesController < ApplicationController
  def dashboard
    @bookings = current_talent.bookings.order(:date)
    @promotions = current_talent.promotions.order(created_at: :desc)
  end
end

app/controllers/talents_controller.rb
class TalentsController < ApplicationController
  before_action :set_talent, only: %i[show edit update]
  skip_before_action :authenticate!, only: :index

  def index
    if params[:query].present?
      sql_query = "talents.name ILIKE :query OR address ILIKE :query OR genres.name ILIKE :query"
      @talents = Talent.joins(:genres).where(sql_query, query: "%#{params[:query]}%").distinct
    else
      @talents = Talent.all.order(updated_at: :desc)
    end
  end

  def show
  end

  def edit
    talent_genres = Genre.where.not(id: [@talent.genres.pluck(:id)]).map do |genre|
      TalentGenre.new(genre: genre, talent: current_talent)
    end
    @all_genres = talent_genres + @talent.talent_genres
    # @talent_genres = @talent.genres
  end

  def update
    @talent.talent_genres.destroy_all
    genre_ids = params[:talent][:genre_ids].split(',').map(&:to_i)
    genre_ids.each do |genre_id|
      TalentGenre.create!(talent: current_talent, genre: Genre.find_by(id: genre_id))
    end
    @talent.update(talent_params)
    redirect_to talent_path(@talent)
  end
end

private

def talent_params
  params.require(:talent).permit(:name, :description, :address, :youtube_link, :instagram_link, :spotify_link, :price, :photo, :address, :email)
end

def set_talent
  begin
    @talent = Talent.find(params[:id])
  rescue
    p "talent not found"
  end
end

app/views/talent/pages/dashboard.html.erb
<div class="container my-5">
  <h3><%= link_to current_talent.name, talent_path(current_talent), class: "text-link"%></h3>
  <div class="flex-space-between">
    <%= link_to talent_path(current_talent) do %>
      <%= cl_image_tag current_talent.photo.key, class: "avatar-large rounded shadow m-3"%>
    <% end %>
    <%= link_to places_path do %>
      <button class="purple_pink_btn m-3">Find a place to play!</button>
    <% end %>
  </div>
  <div>
    <h3 class="mt-3">Bookings</h3>
    <small class="text-muted">Here are the bookings you received from the places</small>
    <div>
      <div class="row justify-content-center">
      <table class = "table_dashboard mt-3">
          <% @bookings.each do |booking|%>
            <div class="dashboard_row">
              <% if booking.status == 'declined' %>
                <tr style="background-color: #BBBBBB;">
              <% elsif booking.status == 'confirmed' %>
                <tr style="background-color: #D488FF;">
              <% else %>
                <tr style="background-color: #EDEDED;">
              <% end %>
                  <td>
                    <%= link_to place_path(booking.place), class: "text-link" do %>
                      <%= cl_image_tag  booking.place.photo.key, class: "avatar rounded shadow"%>
                      <%= booking.place.title %>
                    <% end %>
                  </td>
                  <td><%= booking.date.to_formatted_s(:long) %></td>
                  <td><%= booking.message %></td>
                  <% if booking.status == 'pending' %>
                    <td><%= link_to "confirm", booking_path(booking, status: 'confirmed'), method: :patch, class: "purple_pink_btn"%></td>
                    <td><%= link_to "decline", booking_path(booking, status: 'declined'), method: :patch, class: "black_btn"%></td>
                  <% else  %>
                    <td><%= booking.status %></td>
                    <td><%= link_to "change", booking_path(booking, status: 'pending'), method: :patch, class: "btn-ghost"%></td>
                  <% end %>
              </tr>
            </div>
          <% end %>
        </table>
      </div>
    </div>
  </div>

  <div>
    <h3 class="mt-3">Promotions</h3>
    <small class="text-muted">Here are the promotions you sent to the places</small>
    <div>
      <div class="row justify-content-center">
      <table class = "table_dashboard mt-3">
          <% @promotions.each do |promotion|%>
            <div class="dashboard_row">
              <tr>
                <td>
                    <%= link_to place_path(promotion.place), class: "text-link" do %>
                      <%= cl_image_tag  promotion.place.photo.key, class: "avatar rounded shadow"%>
                      <%= promotion.place.title %>
                    <% end %>
                </td>
                <td><%= promotion.message %></td>
                <td><%= link_to " x ", promotion_path(promotion), method: :delete, class: "btn-ghost", data: { confirm: "Are you sure you want to cancel this promotion?" } %></td>
              </tr>
            </div>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>